### ISSUE TITLE
Bug in A & A === A rewrite

### ISSUE THREAD

**Issue by nathan-beneke** [UMM-CSci/edsger#62]
This works:

```
(p & p) & q
=== < a & a === a >
p & q
```

but this fails:

```
(p & p) & q === r
=== < a & a === a >
p & q === r
```

In fact you can replace the `=== r` part with pretty much any operator and the second proof fails.

**Comment by nathan-beneke** [comment]
This also fails:

```
~((p & p) & q)
=== < a & a === a >
~(p & q)
```

**Comment by NicMcPhee** [comment]
Don't know if this is related to #91 or not.

**Comment by NicMcPhee** [comment]
I think I've found the problem. In `check-match-recursive` there was [an unnecessary check for whether two expressions were non-literals](https://github.com/UMM-CSci/edsger/blob/d5dd7fe8341239f78d08d6bd9f80a08b1fefc1f3/src/edsger/unification.cljs#L44-L50):

```
            [result-list (map (fn [s e]
                                {:equal (= s e)
                                 :match (if (and (list? s) (list? e))
                                          (check-match-recursive s e
                                                                 start-rule
                                                                 end-rule)
                                          (check s e))})
```

Testing that `s` and `e` are lists (non-literals) isn't necessary because that's one of the first things that `check-match-recursive` does, and it will call `check` if necessary. This is a fairly classic case of trying to do much before the recursive call instead of just letting the recursive call do its thing.

If that was the only issue we might have never found it because the extra check isn't an error _per se_. The problem is that the check uses `list?`, which fails if handed a vector. The parser we're using returns vectors, so complex expressions are parsed to nested vectors. These fail the `list?` test, and we fail to recurse appropriately. Simply removing the test appears to both fix the problem and still pass all the tests.

Thanks to @nathan-beneke for his help in documenting this ages ago and creating tests that exposed the problem.

I'll clean up my debugging mess and commit the fix, then create a pull request for review.
